name: Demo Python Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python for Demo
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies for demo Python project  
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Testing the project using pytest
        run: |
         pip install pytest
         pip install pytest-cov
         pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
