name: Demo Python Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python for Demo
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies for demo Python project  
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Linting project with flake8
        run: |
          continue-on-error: true
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Testing the project using pytest
        run: |
         pip install pytest
         pip install pytest-cov
         pytest tests\ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
